blog/urls.py
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index', views.index, name='index'),
    path('about', views.about, name='about'),
    path('services', views.services, name='services'),
    path('contact', views.contact, name='contact'),
    path('blog', views.blog, name='blog'),
    path('blog-post/<int:pk>/', views.blog_post, name='blog-post'),
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new/', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts', views.post_draft_list, name='post_draft_list'),
    path('post/<pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<pk>/remove/', views.post_remove, name='post_remove'),
    re_path(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    re_path(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
	re_path(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

miblog/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login', views.LoginView.as_view(), name='login'),
    path('accounts/logout', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('', include('blog.urls')),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
	# ex: /polls/
	path('', views.index, name='index'),
	# ex: /polls/5/
	path('<int:question_id>/', views.detail, name='detail'),
	# ex: /polls/5/results/
	path('<int:question_id>/results/', views.results, name='results'),
	# ex: /polls/5/vote/
	path('<int:question_id>/vote/', views.vote, name='vote'),

]

blog/models.py
from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=500)
    file = models.FileField(null=True)
    text = RichTextUploadingField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ('title', 'subtitle', 'file', 'text',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from .forms import PostForm, CommentForm
from .models import Post, Comment

def index(request):
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')[:3]
	return render(request, 'web/index.html', {'posts': posts})

def about(request):
	return render(request, 'web/about.html')

def services(request):
	return render(request, 'web/index.html')

def contact(request):
	return render(request, 'web/contact.html')

def blog(request):
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
	paginator = Paginator(posts, 5)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	return render(request, 'web/blog.html', {'page_obj': page_obj})

def blog_post(request, pk):
	post = get_object_or_404(Post, pk=pk)
	return render(request, 'web/blog_post.html', {'post': post})

def post_list(request):
	posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
	return render(request, 'blog/post_list.html', {'posts': posts})

def post_detail(request, pk):
	post = get_object_or_404(Post, pk=pk)
	return render(request, 'blog/post_detail.html', {'post': post})

@login_required
def post_new(request):
	if request.method == 'POST':
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
			return redirect('post_detail', pk=post.pk)
	else:
		form = PostForm()
	return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_edit(request, pk):
	post = get_object_or_404(Post, pk=pk)
	if request.method == 'POST':
		form = PostForm(request.POST, instance=post)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
			return redirect('post_detail', pk=post.pk)
	else:
		form = PostForm(instance=post)
	return render(request, 'blog/post_edit.html', {'form': form})

@login_required
def post_draft_list(request):
	posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
	return render(request, 'blog/post_draft_list.html', {'posts': posts})

@login_required
def post_publish(request, pk):
	post = get_object_or_404(Post, pk=pk)
	post.publish()
	return redirect('post_detail', pk=pk)

@login_required
def post_remove(request, pk):
	post = get_object_or_404(Post, pk=pk)
	post.delete()
	return redirect('post_list')

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post_detail', pk=comment.post.pk)

mysite/polls/views.py
from django.http import HttpResponse, HttpResponse
from django.shortcuts import get_object_or_404, render

from .models import Question

def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	context = {'latest_question_list': latest_question_list}
	return render(request, 'polls/index.html', context)

def detail(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
	response = "You're looking at the results of question %s."
	return HttpResponse(response % question_id)

def vote(request, question_id):
	return HttpResponse("You're voting on question %s." % question_id)

blog/templates/blog/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>Nuevo comentario</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Enviar</button>
    </form>
{% endblock %}

blog/templates/blog/base.html
{% load static %}

<html>
    <head>

        <title>Trayectorias - Asesoría Gerontológica</title>
        <!-- Meta -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">    
        <link rel="shortcut icon" href="{% static 'images/logos/favicon.png' %}">
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

        <link rel="stylesheet" href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}">   
        <!-- Plugins CSS -->    
        <link rel="stylesheet" href="{% static 'plugins/elegant_font/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/flexslider/flexslider.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/owl-carousel/assets/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/owl-carousel/assets/owl.theme.default.min.css' %}"> 
        <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome-all.min.css' %}">

        <!-- Theme CSS -->
        <link id="theme-style" rel="stylesheet" href="{% static 'css/theme-1.css' %}">

    </head>
    <body class="home-page">     
        <div class="header-wrapper header-wrapper-home">
        <!-- ******HEADER****** --> 
            <header id="header" class="header fixed-top">  
                <div class="container">       
                    <h1 class="logo">
                        <a href="{% url 'index' %}"><img class="img_logo" src="{% static 'images/logos/logo_trayectorias.png' %}" alt="" /></a>
                    </h1><!--//logo-->
                    <nav class="main-nav navbar navbar-expand-md navbar-dark" role="navigation">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div id="navbar-collapse" class="navbar-collapse collapse justify-content-end">
                            <ul class="nav navbar-nav">
                                <li class="active nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'about' %}">Quienes Somos</a></li>  
                                <li class="nav-item dropdown"><a class="nav-link disabled" href="{% url 'services' %}">Que hacemos</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'blog' %}">Novedades</a></li>
                                <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contacto</a></li>
                                {% if user.is_authenticated %}
                                    <li class="nav-item last"><a class="nav-link" href="{% url 'logout' %}"><i class="fa fa-times"></i> Salir</a></li>
                                {% else %}
                                    <li class="nav-item last"><a class="nav-link" href="{% url 'login' %}"><i class="fa fa-check"></i> Ingresar</a></li>
                                {% endif %}
                            </ul><!--//nav-->
                        </div><!--//navabr-collapse-->
                    </nav><!--//main-nav-->
                </div><!--//container-->
            </header><!--//header-->

        {% block content %}
        {% endblock %}

    <!--<body>

        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <a href="{% url 'post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                <p class="top-menu">Hola {{ user.username }}! <small>(<a href="{% url 'logout' %}">Log out</a>)</small></p>
            {% else %}
                <a href="{% url 'login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1><a href="/">Django Girls Blog</a></h1>
        </div>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                </div>
            </div>
        </div>

    </body>-->

<!-- ******FOOTER****** --> 
    <footer class="footer">
        <div class="footer-content">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-lg-6 col-md-4 col-12 links-col">
                        <div class="footer-col-inner">
                            <h3 class="sub-title">Accesos rapidos</h3>
                            <ul class="list-unstyled">
                                <li><a href="{% url 'index' %}">Home</a></li>
                                <li><a href="{% url 'about' %}">Quienes Somos</a></li>
                                <li><a href="{% url 'services' %}">Que hacemos</a></li>
                                <li><a href="{% url 'blog' %}">Novedades</a></li>
                                <li><a href="{% url 'contact' %}">Contacto</a></li>
                            </ul>
                        </div><!--//footer-col-inner-->
                    </div><!--//foooter-col-->
                    <div class="footer-col col-lg-6 col-12 contact-col">
                        <div class="footer-col-inner">
                            <h3 class="sub-title">Contactanos</h3>
                            <p class="intro"></p>
                            <div class="row">
                                <p class="tel col-lg-12 col-md-4 col-12"><span class="fs1" aria-hidden="true" data-icon="&#x77;"></span><a href="tel:+08001234567">0800 123 4567</a></p>
                                <p class="email col-lg-12 col-md-4 col-12"><span class="fs1" aria-hidden="true" data-icon="&#xe010;"></span><a href="#">hello@yourdevstudio.com</a></p> 
                            </div> 
                        </div><!--//footer-col-inner-->            
                    </div><!--//foooter-col-->   
                </div>   
            </div>        
        </div><!--//footer-content-->
        <div class="bottom-bar">
            <div class="container center">                                   
                <ul class="social-icons list-inline">
                    <li class="list-inline-item"><a href="https://twitter.com/3rdwave_themes"><i class="fa fa-twitter"></i></a></li>                        
                    <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li class="list-inline-item"><a href="https://www.facebook.com/3rdwavethemes"><i class="fa fa-instagram"></i></a></li>                  
                </ul>
                <a href="#" class="fa fa-twitter"></a>
            </div><!--//container-->
        </div><!--//bottom-bar-->
    </footer><!--//footer-->
 
    <!-- Main Javascript -->
    <script type="text/javascript" src="{% static 'plugins/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plugins/popper.min.js' %}"></script> 
    <script type="text/javascript" src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script> 
    <script type="text/javascript" src="{% static 'plugins/back-to-top.js' %}"></script>                                                                            
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>

    <!-- Flexslider -->    
    <script type="text/javascript" src="{% static 'plugins/flexslider/jquery.flexslider-min.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/flexslider-custom.js' %}"></script>     

    <!-- Form Validation -->
    <script type="text/javascript" src="{% static 'plugins/jquery.validate.min.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/form-validation-custom.js' %}"></script>

    <!-- Form iOS fix -->
    <script type="text/javascript" src="{% static 'plugins/isMobile/isMobile.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/form-mobile-fix.js' %}"></script>

    <!-- Owl Carousel -->
    <script type="text/javascript" src="{% static 'plugins/owl-carousel/owl.carousel.min.js' %}"></script> 
    <script type="text/javascript" src="{% static 'js/owl-custom.js' %}"></script> 
    
</body>
</html> 

blog/templates/blog/post_detail.html
{%  extends 'blog/base.html' %}
{% load static %}

{% block content %}

        <div class="bg-slider-wrapper">
            {% if post.file %}
                <img class="img-fluid" style="max-height:400px;" src="{{ post.file.url }}" alt=""/>
            {% else %}
                <img class="img-fluid" src="{% static 'images/background/blog2-background.jpg' %}" alt=""/>
            {% endif %}
        </div><!--//bg-slider-wrapper--> 
    </div><!--//header-wrapper-->

     <!-- ******Blog Post****** -->
    <div class="blog-post-wrapper container">            
        <div class="row">
            <div class="col-lg-10 col-md-10 mx-auto">               
                <article class="post">
                    {% if not post.published_date %}
                        <a class="btn btn-primary" href="{% url 'post_publish' pk=post.pk %}">Publicar</a>
                    {% endif %}
                    {% if user.is_authenticated %}
                        <a class="btn btn-primary" href="{% url 'post_edit' pk=post.pk %}">Editar</a>
                        <a class="btn btn-danger" href="{% url 'post_remove' pk=post.pk %}">Eliminar</span></a>
                    {% endif %}
                    <h2 class="title">{{ post.title }}</h2>
                    <h3 class="subtitle">{{ post.subtitle }}</h3>
                    <p class="post-meta">Posted by <a href="#">{{ post.author }}</a> on {{ post.published_date }}</p>
                    <div class="content">
                        <div class="text">
                            {{ post.text|safe }}
                        </div>
                    </div>
                    <hr>

                    <a class="btn btn-default" href="{% url 'add_comment_to_post' pk=post.pk %}">Add comment</a>
                	{% for comment in post.comments.all %}
                		{% if user.is_authenticated or comment.approved_comment %}
                		    <div class="comment">
                		        <div class="date">{{ comment.created_date }}
                		        	{% if not comment.approved_comment %}
                                		<a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                                		<a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                            		{% endif %}
                		        </div>
                		        <strong>{{ comment.author }}</strong>
                		        <p>{{ comment.text|linebreaks }}</p>
                		    </div>
                		{% endif %}
                	{% empty %}
                	    <p>No hay comentarios todavia!</p>
                	{% endfor %}
                </article><!--//post-->                                      
            </div><!--//blog-entry-->
        </div><!--//row-->
    </div><!--//blog-->

{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
		<div class="bg-slider-wrapper">
			<img class="img-fluid" src="{% static 'images/background/blog2-background.jpg' %}" alt=""/>
		</div><!--//bg-slider-wrapper--> 
		<section class="promo section">
            <div class="container text-center">
            	<h2 class="title">
					<span class="middle">Borradores</span>
				</h2>
            </div><!--//container-->
        </section><!--//promo-->
    </div><!--//header-wrapper-->

    <section id="blog-list" class="blog-list section">
        <div class="container">
			<div class="row">
				<div class="col-lg-10 col-md-10 mx-auto">
				    {% for post in posts %}
				    	<div class="post-preview">
					        <a href="{% url 'post_detail' pk=post.pk %}">
								<h2 class="post-title">{{ post.title }}</h2>
								<h3 class="post-subtitle">{{ post.subtitle }}</h3>
							</a>
							<p class="post-meta">Posted by <a href="#">{{ post.author }}</a> on {{ post.published_date }}</p>
					    </div>
						<hr>
				    {% empty %}
		    			<p>No hay borradores creados!</p>
				    {% endfor %}
				</div>
			</div>
		</div>
	</section>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}
{% load static %}

{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}

{% block content %}
		<div class="bg-slider-wrapper">
			<img class="img-fluid" src="{% static 'images/background/blog2-background.jpg' %}" alt=""/>
		</div><!--//bg-slider-wrapper--> 
		<section class="promo section">
            <div class="container text-center">
            	<h2 class="title">
					<span class="middle">New post</span>
				</h2>
            </div><!--//container-->
        </section><!--//promo-->
    </div><!--//header-wrapper-->

    <div class="blog-post-wrapper container">            
        <div class="row">
        	<div class="col-lg-10 col-md-10 mx-auto">
				<form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
					{{ form.media }}
					{{ form.as_p }}
					<button type="submit" class="save btn btn-primary">Guardar</button>
				</form>
			</div>
		</div>
	</div>
{% endblock %}

blog/templates/blog/post_list.html
{%  extends 'web/blog.html' %}

{% block post_list %}
    {% for post in posts %}
        <div class="post">
            <div class="date"><p>Publicado: {{ post.published_date }}</p></div>

            <h2><a href="{% url 'post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
            <p>{{ post.text|safe }}</p>
            <a href="{% url 'post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
        </div>
    {% endfor %}
{% endblock post_list %}

blog/templates/web/blog.html
{%  extends 'blog/base.html' %}
{% load static %}

{% block content %}

		<div class="bg-slider-wrapper">
			<img class="img-fluid" src="{% static 'images/background/blog-background.jpg' %}" alt=""/>
        </div><!--//bg-slider-wrapper--> 
        <section class="promo section">
            <div class="container text-center">  
				<h2 class="title">
					<span class="middle">Novedades</span>
                    <span class="bottom-small">Homogeneizar a la gente mayor en función de la edad supone ignorar la enorme diversidad que existe entre las personas 
					ancianas y pasar por alto la aportación efectuada por ellas a la vida y, además, oscurece su papel como apoyo al ejercer en trabajos 
					voluntarios y en la atención informal que brindan sobre todo a su cónyuge y a la vecindad” (Alber y Ginn, 1990).<br>
					Desde Trayectorias reflexionamos acerca de la importancia de desmitificar la construcción social que homogeiniza la vejez y de visibilizar 
					los aportes que brindan lxs mayores a nuestra sociedad.</span>
				</h2>
            </div><!--//container-->
        </section><!--//promo-->
    </div><!--//header-wrapper-->
	
	<!-- ******Latest blog Section****** -->
    <section id="blog-list" class="blog-list section">
        <div class="container">
			<div class="row">
				{% if user.is_authenticated %}
					<div class="col-lg-10 col-md-10 mx-auto">
						<a class="btn btn-primary" href="{% url 'post_new' %}">Nuevo</a>
						<a class="btn btn-primary" href="{% url 'post_draft_list' %}">Borradores</a>
					</div>
				{% endif %}
				<div class="col-lg-10 col-md-10 mx-auto">
					{% for posts in page_obj %}
						<div class="post-preview">
					        <a href="{% url 'blog-post' pk=posts.pk %}">
								<h2 class="post-title">{{ posts.title }}</h2>
								<h3 class="post-subtitle">{{ posts.subtitle }}</h3>
							</a>
							<p class="post-meta">Posted by <a href="#">{{ posts.author }}</a> on {{ posts.published_date }}</p>
					    </div>
					<hr>
				    {% empty %}
    					<p>No hay entradas creadas!</p>
				    {% endfor %}
					
					<!-- Pager -->
					<div class="pagination-container text-center">
						<ul class="pagination justify-content-center">
							{% if page_obj.has_previous %}
								<li class="page-item">
									<a class="page-link" href="?page={{ page_obj.previous_page_number }}" arial-label="previous">
										<span aria-hidden="true">&laquo;</span>
										<span class="sr-only">Anterior</span>
									</a>
								</li>
					        {% endif %}
					        <li class="page-item">
						        <span class="current_pages">
						            Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}
						            &nbsp;
						        </span>
						    </li>

					        {% if page_obj.has_next %}
					        	<li class="page-item">
									<a class="page-link" href="?page={{ page_obj.next_page_number }}">
										<span aria-hidden="true">&raquo;</span>
										<span class="sr-only">Next</span>
									</a>
								</li>
					        {% endif %}
						</ul><!--//pagination-->
					</div><!--//pagination-container-->
				</div>
			</div>
		  </div>
    </section><!--//latest-blog-->
	
{% endblock %}

blog/templates/web/contact.html
{%  extends 'blog/base.html' %}
{% load static %}

{% block content %}

		<div class="bg-slider-wrapper">
			<img class="img-fluid" src="{% static 'images/background/blog4-background.jpg' %}" alt=""/>
        </div><!--//bg-slider-wrapper-->   
        <section class="promo section">
            <div class="container text-center">        
				<h2 class="title">
					<span class="middle">Contact Us</span>
                    <span class="bottom">Get in touch if you have a project or want to find out more about our services. We'd love to hear from you!</span>
				</h2>
            </div><!--//container-->
        </section><!--//promo-->
    </div><!--//header-wrapper-->
    
    <!-- ******Contact Section****** --> 
    <section class="contact-section section">
        <div class="container">
            <h2 class="title text-center">Start your project today</h2>
            <p class="intro text-center">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed laoreet tortor consequat nisi scelerisque commodo etiam justo sapien.</p>
            <ul class="contact-info list-inline text-center">
                <li class="tel list-inline-item"><span class="fs1" aria-hidden="true" data-icon="&#x77;"></span><br /> <a href="+0800123456">0800 123 4567</a></li>
                <li class="email list-inline-item"><span class="fs1" aria-hidden="true" data-icon="&#xe010;"></span><br /> <a href="#">hello@yourdevstudio.com</a></li>
            </ul>
            <form id="contact-form" class="contact-form form" method="post" action="#">
                
                <div class="row text-center">
                    <div class="contact-form-inner col-lg-8 col-12 mr-lg-auto ml-lg-auto">
                        <div class="row">                                                                                       
                            <div class="col-md-6 col-12 form-group">
                                <label class="sr-only" for="cname">Your name</label>
                                <input type="text" class="form-control" id="cname" name="name" placeholder="Your name" minlength="2" required>
                            </div>
                            <div class="col-md-6 col-12 form-group">
                                <label class="sr-only" for="cemail">Email address</label>
                                <input type="email" class="form-control" id="cemail" name="email" placeholder="Your email address" required>
                            </div>
                            <div class="col-12 form-group">
                                <label class="sr-only" for="cmessage">Your message</label>
                                <textarea class="form-control" id="cmessage" name="message" placeholder="Enter your message" rows="12" required></textarea>
                            </div>
                             <div class="col-12 form-group">
                                <button type="submit" class="btn btn-block btn-cta btn-cta-primary">Send Message</button>
                            </div>                           
                        </div><!--//row-->
                    </div>
                </div><!--//row-->
                <div id="form-messages"></div>
            </form><!--//contact-form-->
        </div><!--//container-->
    </section><!--//contact-section-->
    
{% endblock %}

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}
	<p>
		<strong>{{ error_message }}</strong>
	</p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
	{% for choice in question.choice_set.all %}
	    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
	    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
	{% endfor %}
	<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}